[package]
name = "imgui-opengl3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
imgui-opengl-renderer = "0.11"
gl_loader = "0.1"